// Generated by delombok at Sat May 23 12:46:34 IST 2026
package com.llbeauty.controller;

import com.llbeauty.repository.ProductRepository;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;

@Controller
public class HomeController {
    private final ProductRepository productRepository;
    private final com.llbeauty.repository.ContactMessageRepository contactMessageRepository;
    private final com.llbeauty.repository.SalonServiceRepository salonServiceRepository;

    public HomeController(final ProductRepository productRepository,
                          final com.llbeauty.repository.ContactMessageRepository contactMessageRepository,
                          final com.llbeauty.repository.SalonServiceRepository salonServiceRepository) {
        this.productRepository = productRepository;
        this.contactMessageRepository = contactMessageRepository;
        this.salonServiceRepository = salonServiceRepository;
    }

    @GetMapping("/")
    public String home(Model model) {
        model.addAttribute("products", productRepository.findAll());
        return "index";
    }

    @GetMapping("/about")
    public String about() {
        return "about";
    }

    @GetMapping("/salon")
    public String salon(Model model) {
        model.addAttribute("services", salonServiceRepository.findAll());
        return "salon";
    }

    @GetMapping("/franchise")
    public String franchise() {
        return "franchise";
    }

    @GetMapping("/contact")
    public String contact() {
        return "contact";
    }

    @org.springframework.web.bind.annotation.PostMapping("/contact/submit")
    public String submitContact(
            @org.springframework.web.bind.annotation.RequestParam("name") String name,
            @org.springframework.web.bind.annotation.RequestParam("email") String email,
            @org.springframework.web.bind.annotation.RequestParam("phone") String phone,
            @org.springframework.web.bind.annotation.RequestParam("subject") String subject,
            @org.springframework.web.bind.annotation.RequestParam("message") String message,
            org.springframework.web.servlet.mvc.support.RedirectAttributes redirectAttributes) {
            
        com.llbeauty.entity.ContactMessage msg = new com.llbeauty.entity.ContactMessage(name, email, phone, subject, message);
        contactMessageRepository.save(msg);
        
        redirectAttributes.addFlashAttribute("successMessage", "Thank you for reaching out! Our team will get back to you shortly.");
        return "redirect:/contact";
    }
}
