// Generated by delombok at Sat May 23 12:46:34 IST 2026
package com.llbeauty.controller;

import com.llbeauty.entity.Product;
import com.llbeauty.repository.ProductRepository;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import java.util.List;

@Controller
public class ShopController {
    private final ProductRepository productRepository;

    @GetMapping("/shop")
    public String shop(Model model, 
                       @RequestParam(value = "category", required = false) String category,
                       @RequestParam(value = "search", required = false) String search) {
        List<Product> products;
        String trimmedCategory = (category != null && !category.trim().isEmpty()) ? category.trim() : null;
        String trimmedSearch = (search != null && !search.trim().isEmpty()) ? search.trim() : null;

        if (trimmedCategory != null || trimmedSearch != null) {
            products = productRepository.searchProductsList(trimmedCategory, trimmedSearch, null);
        } else {
            products = productRepository.findAll();
        }
        model.addAttribute("products", products);
        model.addAttribute("selectedCategory", category);
        model.addAttribute("selectedSearch", search);
        return "shop";
    }

    @java.lang.SuppressWarnings("all")
    
    @org.springframework.beans.factory.annotation.Autowired
    public ShopController(final ProductRepository productRepository) {
        this.productRepository = productRepository;
    }
}
