// Generated by delombok at Sat May 23 12:46:34 IST 2026
package com.llbeauty.controller;

import com.llbeauty.dto.AdminLoginRequest;
import com.llbeauty.dto.OtpVerifyRequest;
import com.llbeauty.dto.RegisterRequest;
import com.llbeauty.service.AuthService;
import jakarta.servlet.http.Cookie;
import jakarta.servlet.http.HttpServletResponse;
import jakarta.validation.Valid;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.servlet.mvc.support.RedirectAttributes;

@Controller
@RequestMapping("/auth")
public class AuthController {
    @java.lang.SuppressWarnings("all")
    
    private static final org.slf4j.Logger log = org.slf4j.LoggerFactory.getLogger(AuthController.class);
    private final AuthService authService;

    // ---- GET LOGIN PAGE ----
    @GetMapping("/login")
    public String loginPage(@RequestParam(value = "redirect", required = false) String redirect, Model model) {
        model.addAttribute("redirect", redirect);
        return "login";
    }

    // ---- POST SEND LOGIN OTP ----
    @PostMapping("/login/send-otp")
    public String sendLoginOtp(@RequestParam("mobile") String mobile, @RequestParam(value = "redirect", required = false) String redirect, RedirectAttributes redirectAttributes) {
        if (mobile == null || !mobile.matches("^[6-9]\\d{9}$")) {
            redirectAttributes.addFlashAttribute("error", "Enter a valid 10-digit mobile number");
            return "redirect:/auth/login" + (redirect != null ? "?redirect=" + redirect : "");
        }
        boolean sent = authService.sendLoginOtp(mobile);
        if (!sent) {
            redirectAttributes.addFlashAttribute("error", "Mobile number not registered. Please sign up first.");
            return "redirect:/auth/login" + (redirect != null ? "?redirect=" + redirect : "");
        }
        redirectAttributes.addFlashAttribute("info", "OTP sent successfully! Enter 1234 to verify.");
        return "redirect:/auth/verify?mobile=" + mobile + (redirect != null ? "&redirect=" + redirect : "");
    }

    // ---- GET REGISTER PAGE ----
    @GetMapping("/register")
    public String registerPage(Model model) {
        model.addAttribute("registerRequest", new RegisterRequest());
        return "register";
    }

    // ---- POST REGISTER ----
    @PostMapping("/register")
    public String register(@Valid @ModelAttribute("registerRequest") RegisterRequest request, BindingResult bindingResult, RedirectAttributes redirectAttributes) {
        if (bindingResult.hasErrors()) {
            return "register";
        }
        boolean registered = authService.registerUser(request);
        if (!registered) {
            bindingResult.rejectValue("mobile", "duplicate", "Mobile number is already registered.");
            return "register";
        }
        redirectAttributes.addFlashAttribute("info", "Registration successful! OTP sent to mobile. Enter 1234.");
        return "redirect:/auth/verify?mobile=" + request.getMobile();
    }

    // ---- GET VERIFY OTP PAGE ----
    @GetMapping("/verify")
    public String verifyPage(@RequestParam("mobile") String mobile, @RequestParam(value = "redirect", required = false) String redirect, Model model) {
        model.addAttribute("mobile", mobile);
        model.addAttribute("redirect", redirect);
        return "verify";
    }

    // ---- POST VERIFY OTP ----
    @PostMapping("/verify")
    public String verifyOtp(@RequestParam("mobile") String mobile, @RequestParam("otp") String otp, @RequestParam(value = "redirect", required = false) String redirect, HttpServletResponse response, RedirectAttributes redirectAttributes) {
        String token = authService.verifyOtpAndLogin(mobile, otp);
        if (token == null) {
            redirectAttributes.addFlashAttribute("error", "Invalid or expired OTP. Please try again (Dummy OTP is 1234).");
            return "redirect:/auth/verify?mobile=" + mobile + (redirect != null ? "&redirect=" + redirect : "");
        }
        // Set HttpOnly Cookie for authentication
        Cookie cookie = new Cookie("LLB_TOKEN", token);
        cookie.setHttpOnly(true);
        cookie.setPath("/");
        cookie.setMaxAge(24 * 60 * 60); // 24 hours
        response.addCookie(cookie);
        log.info("User {} successfully logged in.", mobile);
        if (redirect != null && !redirect.trim().isEmpty() && !redirect.contains("/auth/")) {
            return "redirect:" + redirect;
        }
        return "redirect:/";
    }

    // ---- GET ADMIN LOGIN PAGE ----
    @GetMapping("/admin/login")
    public String adminLoginPage() {
        return "admin_login";
    }

    // ---- POST ADMIN LOGIN ----
    @PostMapping("/admin/login")
    public String adminLogin(@RequestParam("email") String email, @RequestParam("password") String password, HttpServletResponse response, RedirectAttributes redirectAttributes) {
        String token = authService.adminLogin(email, password);
        if (token == null) {
            redirectAttributes.addFlashAttribute("error", "Invalid admin email or password");
            return "redirect:/auth/admin/login";
        }
        // Set HttpOnly Cookie for authentication
        Cookie cookie = new Cookie("LLB_TOKEN", token);
        cookie.setHttpOnly(true);
        cookie.setPath("/");
        cookie.setMaxAge(24 * 60 * 60); // 24 hours
        response.addCookie(cookie);
        log.info("Admin {} successfully logged in.", email);
        return "redirect:/admin/dashboard"; // Redirect to admin dashboard
    }

    @java.lang.SuppressWarnings("all")
    
    public AuthController(final AuthService authService) {
        this.authService = authService;
    }
}
