// Generated by delombok at Sat May 23 12:46:34 IST 2026
package com.llbeauty.controller;

import com.llbeauty.repository.ProductRepository;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;

@Controller
public class HomeController {
    private final ProductRepository productRepository;

    @GetMapping("/")
    public String home(Model model) {
        model.addAttribute("products", productRepository.findAll());
        return "index";
    }

    @GetMapping("/about")
    public String about() {
        return "about";
    }

    @GetMapping("/salon")
    public String salon() {
        return "salon";
    }

    @GetMapping("/franchise")
    public String franchise() {
        return "franchise";
    }

    @java.lang.SuppressWarnings("all")
    
    public HomeController(final ProductRepository productRepository) {
        this.productRepository = productRepository;
    }
}
